In [1]:
import nltk
import pandas as pd

In [2]:
# setting the variables
language = "en"
filename = "{}_top_10".format(language)

In [3]:
# gathering the data
df = pd.read_csv("data/lemmatize/{0}/{1}.csv".format(language, filename))

In [4]:
# removing the relative position column
df = df.drop("Unnamed: 0", axis=1)

In [5]:
#df.head()

In [9]:
# creating a list to hold the POS tagged words
# TODO: improve code structure
pos_col = list()

for row in df.iterrows():
    # TODO: fix this workaround of needing a list to POS tag
    word = [row[1][0]]
    #print("word", word)
    if type(word[0]) == type("meString"):
        # fetching the tuple from the list
        tagged_word = nltk.pos_tag(word)[0]
    #print("tag", tagged_word)
    # add to list
        pos_col.append(tagged_word)
    else:
        pos_col.append([word, None])

In [10]:
#pos_col

In [11]:
# create a Series object
# TODO: this should be able to happen right away
pos = pd.Series(pos_col)
#pos

In [12]:
# add the new info to a copy of the dataframe
pdf = pd.concat([df, pos], axis=1, names=["word", "frequency", "POS"])
# rename for prettiness
pdf.columns = ["word", "frequency", "POS"]

In [13]:
pdf.head()

  word  frequency         POS
0  you   79000070  (you, PRP)
1    i   72589160     (i, NN)
2  the   62029246   (the, DT)
3   to   45655734    (to, TO)
4    a   39152928     (a, DT)

In [14]:
pdf.tail()

            word  frequency                POS
9995      signor       6659       (signor, NN)
9996        lace       6659         (lace, NN)
9997   bloodshed       6659   (bloodshed, VBN)
9998  confronted       6652  (confronted, VBN)
9999        hash       6652         (hash, NN)

In [15]:
pdf

              word  frequency                  POS
0              you   79000070           (you, PRP)
1                i   72589160              (i, NN)
2              the   62029246            (the, DT)
3               to   45655734             (to, TO)
4                a   39152928              (a, DT)
5               it   36643987            (it, PRP)
6              and   28128688            (and, CC)
7             that   27513932           (that, IN)
8               of   24412779             (of, IN)
9               in   20157294             (in, IN)
10              is   19816572            (is, VBZ)
11            what   19056829           (what, WP)
12              we   18715575            (we, PRP)
13              me   17671591            (me, PRP)
14            this   15823163           (this, DT)
15              he   14856510            (he, PRP)
16             for   13756823            (for, IN)
17              on   13611399             (on, IN)
18              my   13260623           (my, PRP$)
19            your   12774217         (your, PRP$)
20            have   12612251           (have, VB)
21              no   12100798             (no, DT)
22              do   11961917             (do, VB)
23             was   11413483           (was, VBD)
24             are   11394151           (are, VBP)
25             don   11390146            (don, NN)
26             not   11350356            (not, RB)
27              be   11258948             (be, VB)
28            know   10582215           (know, VB)
29             can   10360898            (can, MD)
...            ...        ...                  ...
9970         rossi       6684          (rossi, NN)
9971       pauline       6683        (pauline, NN)
9972       clearer       6681        (clearer, NN)
9973        fusion       6681         (fusion, NN)
9974        batter       6678         (batter, NN)
9975      cowardly       6678       (cowardly, RB)
9976        shades       6678        (shades, NNS)
9977       uptight       6677        (uptight, JJ)
9978      applying       6676      (applying, VBG)
9979       doubted       6676       (doubted, VBN)
9980       porsche       6675        (porsche, NN)
9981         iraqi       6674          (iraqi, NN)
9982         forum       6674          (forum, NN)
9983     powerless       6673      (powerless, NN)
9984        scrape       6672         (scrape, NN)
9985         turks       6669         (turks, NNS)
9986     nightfall       6668      (nightfall, NN)
9987        chiefs       6667        (chiefs, NNS)
9988     nervously       6665      (nervously, RB)
9989         brink       6665          (brink, NN)
9990  applications       6664  (applications, NNS)
9991        shoved       6663        (shoved, VBN)
9992          tito       6663           (tito, NN)
9993        stains       6663        (stains, NNS)
9994    englishman       6660     (englishman, NN)
9995        signor       6659         (signor, NN)
9996          lace       6659           (lace, NN)
9997     bloodshed       6659     (bloodshed, VBN)
9998    confronted       6652    (confronted, VBN)
9999          hash       6652           (hash, NN)

[10000 rows x 3 columns]

In [22]:
def get_POS_info(POS):
    print(nltk.help.upenn_tagset(POS))

In [27]:
get_POS_info("DT")

DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
None